#!/bin/bash
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "         ABDULLAH'S SCRIPT CHEATSHEET    "
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  gq          commit + push current repo"
echo "  newrepo     create new GitHub repo + open in VS Code"
echo "  gclone      pick a GitHub repo and clone it"
echo "  backup      zip current folder, e.g: backup . or backup myfolder"
echo "  end         go to Users folder and exit terminal"
echo "  cs          show this cheatsheet"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
